'use client';

import { useState } from 'react';
import { useI18n } from '@/lib/i18n';
import { Gauge } from './Gauge';
import { API_BASE } from '@/lib/config';
import type { ReportData } from './PayPalFlow';

interface PaidReportProps {
  data: ReportData;
  onReset: () => void;
}

export function PaidReport({ data, onReset }: PaidReportProps) {
  const { t, lang } = useI18n();
  const [copied, setCopied] = useState(false);

  const rd = data.report_data?.report || data.report_data || {};
  const report = rd as Record<string, unknown>;
  const breakdown = (report.score_breakdown || {}) as Record<string, unknown>;
  const score = (breakdown.score as number) || 0;
  const subScores = (report.sub_scores || {}) as Record<string, number>;
  const competitors = (report.competitors || []) as Array<{
    name: string; url?: string; stars?: number; description?: string;
    language?: string; activity?: { badge?: string; label?: string; days_since_update?: number };
    found_via_angles?: string[];
  }>;
  const analysis = (report.strategic_analysis || '') as string;
  const crowd = (report.crowd_intelligence || {}) as Record<string, unknown>;
  const angles = (report.search_angles || []) as string[];
  const sourceBars = (breakdown.source_bars || []) as Array<{ source: string; signals: number; percentage: number }>;

  // Sub-dimension scores
  const subDims: Array<{ key: string; label: string; value: number | null }> = [
    { key: 'competition_density', label: lang === 'zh' ? '競爭密度' : 'Competition Density', value: subScores.competition_density ?? null },
    { key: 'market_maturity', label: lang === 'zh' ? '市場成熟度' : 'Market Maturity', value: subScores.market_maturity ?? null },
    { key: 'community_buzz', label: lang === 'zh' ? '社群熱度' : 'Community Buzz', value: subScores.community_buzz ?? null },
  ];
  const ecoVal = Math.max(subScores.ecosystem_depth_npm || 0, subScores.ecosystem_depth_pypi || 0);
  if (subScores.ecosystem_depth_npm != null || subScores.ecosystem_depth_pypi != null) {
    subDims.push({ key: 'ecosystem_depth', label: lang === 'zh' ? '生態深度' : 'Ecosystem Depth', value: ecoVal });
  }

  const handleCopyToAI = () => {
    const lines: string[] = [];
    lines.push('## Verified Market Intelligence Report');
    lines.push(`> Generated by Mnemox Idea Reality · ${(report.verified_at as string) || new Date().toISOString()} · All data verified from live APIs`);
    lines.push('');
    lines.push(`### Idea: ${data.idea_text || ''}`);
    lines.push('');
    lines.push(`### Overall Score: ${score}/100 — ${(breakdown.duplicate_likelihood as string) || 'unknown'} duplicate likelihood`);
    lines.push('');

    const validDims = subDims.filter(d => d.value != null);
    if (validDims.length) {
      lines.push('### Sub-Dimension Scores');
      validDims.forEach(d => lines.push(`- ${d.label}: ${Math.round(d.value!)}/100`));
      lines.push('');
    }
    if (angles.length) {
      lines.push('### Search Angles Used');
      angles.forEach((a, i) => lines.push(`${i + 1}. "${a}"`));
      lines.push('');
    }
    if (competitors.length) {
      lines.push('### Top Competitors');
      lines.push('| # | Project | Stars | Language | Activity |');
      lines.push('|---|---------|-------|----------|----------|');
      competitors.slice(0, 10).forEach((c, i) => {
        const act = c.activity || {};
        lines.push(`| ${i + 1} | ${c.name} | ${(c.stars || 0).toLocaleString()} | ${c.language || '-'} | ${act.label || '-'} |`);
      });
      lines.push('');
    }
    const crowdCount = crowd.similar_count as number;
    if (crowdCount > 0) {
      lines.push('### Crowd Intelligence');
      lines.push(`${crowdCount} builders searched similar ideas. Average score: ${crowd.avg_score || 0}/100.`);
      lines.push('');
    }
    if (analysis) {
      lines.push('### Strategic Analysis');
      lines.push(analysis);
      lines.push('');
    }
    lines.push('---');
    lines.push('Based on this verified market data, help me create a product positioning plan that addresses the gaps in the competitive landscape.');

    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const likelihoodColor = (l: string) => {
    if (l === 'high') return 'text-danger';
    if (l === 'medium') return 'text-amber';
    return 'text-neon-green';
  };

  return (
    <div>
      {/* Score Header */}
      <div className="mb-8 text-center">
        <Gauge score={score} label={t('check_reality_signal')} />
        {data.idea_text && (
          <p className="mt-4 text-sm text-txt-dim max-w-[480px] mx-auto">{data.idea_text}</p>
        )}
        {typeof breakdown.summary === 'string' && breakdown.summary && (
          <p className="mt-2 font-mono text-sm text-txt-dim">{breakdown.summary}</p>
        )}
        {typeof breakdown.duplicate_likelihood === 'string' && breakdown.duplicate_likelihood && (
          <p className="mt-1 font-mono text-xs">
            {lang === 'zh' ? '重複可能性：' : 'Duplicate likelihood: '}
            <span className={`font-bold ${likelihoodColor(breakdown.duplicate_likelihood)}`}>
              {t(`check_likelihood_${breakdown.duplicate_likelihood}` as 'check_likelihood_low')}
            </span>
          </p>
        )}
      </div>

      {/* Source Distribution Bars */}
      {sourceBars.length > 0 && (
        <section className="mb-8 rounded-xl border border-border bg-bg-card p-6">
          <h3 className="mb-4 font-mono text-[11px] uppercase tracking-[2px] text-cyan">
            {lang === 'zh' ? '來源分佈' : 'Source Distribution'}
          </h3>
          <div className="space-y-3">
            {sourceBars.map(bar => (
              <div key={bar.source}>
                <div className="flex justify-between font-mono text-xs text-txt-dim mb-1">
                  <span>{bar.source}</span>
                  <span>{bar.signals.toLocaleString()} signals ({bar.percentage}%)</span>
                </div>
                <div className="h-2 rounded-full bg-border overflow-hidden">
                  <div
                    className="h-full rounded-full bg-cyan transition-all duration-700"
                    style={{ width: `${bar.percentage}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Sub-Dimension Scores */}
      {subDims.some(d => d.value != null) && (
        <section className="mb-8 rounded-xl border border-border bg-bg-card p-6">
          <h3 className="mb-4 font-mono text-[11px] uppercase tracking-[2px] text-cyan">
            {t('check_preview_subdim')}
          </h3>
          <div className="space-y-4">
            {subDims.filter(d => d.value != null).map(dim => (
              <div key={dim.key}>
                <div className="flex justify-between font-mono text-xs text-txt-dim mb-1.5">
                  <span>{dim.label}</span>
                  <span className="font-bold text-txt">{Math.round(dim.value!)}</span>
                </div>
                <div className="h-2.5 rounded-full bg-border overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all duration-700"
                    style={{
                      width: `${Math.min(Math.max(dim.value!, 0), 100)}%`,
                      backgroundColor: dim.value! > 70 ? '#ff3366' : dim.value! > 40 ? '#ffaa00' : '#00ff88',
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Competitors */}
      {competitors.length > 0 && (
        <section className="mb-8">
          <h3 className="mb-4 font-mono text-[11px] uppercase tracking-[2px] text-cyan">
            {t('check_preview_comp')} ({competitors.length})
          </h3>
          <div className="space-y-3">
            {competitors.map((c, i) => {
              const act = c.activity || {};
              return (
                <div key={i} className="rounded-lg border border-border bg-bg-card p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        {act.badge && (
                          <span className="text-sm">{act.badge}</span>
                        )}
                        {c.url ? (
                          <a href={c.url} target="_blank" rel="noopener noreferrer" className="font-medium text-accent hover:underline truncate">
                            {c.name}
                          </a>
                        ) : (
                          <span className="font-medium text-txt">{c.name}</span>
                        )}
                        {c.language && (
                          <span className="rounded bg-border px-1.5 py-0.5 font-mono text-[10px] text-txt-muted">{c.language}</span>
                        )}
                      </div>
                      {c.description && <p className="text-sm text-txt-dim line-clamp-2">{c.description}</p>}
                      <div className="mt-1 flex items-center gap-2 text-[11px] font-mono text-txt-muted">
                        {act.label && <span>{act.label}</span>}
                        {act.days_since_update != null && (
                          <span>· {act.days_since_update === 0 ? 'today' : `${act.days_since_update}d ago`}</span>
                        )}
                      </div>
                    </div>
                    {c.stars != null && (
                      <span className="shrink-0 font-mono text-xs text-amber">{c.stars.toLocaleString()}★</span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* Crowd Intelligence */}
      {(crowd.similar_count as number) > 0 && (
        <section className="mb-8 rounded-xl border border-border bg-bg-card p-6">
          <h3 className="mb-4 font-mono text-[11px] uppercase tracking-[2px] text-cyan">
            {t('check_comp_crowd')}
          </h3>
          <div className="flex flex-wrap gap-6 mb-3">
            <div className="text-center">
              <div className="font-mono text-xl font-bold text-cyan">{crowd.similar_count as number}</div>
              <div className="font-mono text-[11px] text-txt-dim">{lang === 'zh' ? '相似查詢' : 'similar queries'}</div>
            </div>
            <div className="text-center">
              <div className="font-mono text-xl font-bold text-cyan">{crowd.avg_score as number}</div>
              <div className="font-mono text-[11px] text-txt-dim">{lang === 'zh' ? '平均分數' : 'avg score'}</div>
            </div>
            {(crowd.total_database_queries as number) > 0 && (
              <div className="text-center">
                <div className="font-mono text-xl font-bold text-cyan">{(crowd.total_database_queries as number).toLocaleString()}</div>
                <div className="font-mono text-[11px] text-txt-dim">{lang === 'zh' ? '資料庫總量' : 'total in database'}</div>
              </div>
            )}
          </div>
          {typeof crowd.message === 'string' && crowd.message && <p className="text-sm text-txt-dim">{crowd.message}</p>}
          {typeof crowd.score_comparison === 'string' && crowd.score_comparison && (
            <p className="mt-1 text-xs text-txt-muted">
              {lang === 'zh' ? '你的分數' : 'Your score is'} <strong className="text-txt">{crowd.score_comparison}</strong> {lang === 'zh' ? '相似查詢的平均值' : 'the average of similar queries'}.
            </p>
          )}
        </section>
      )}

      {/* Strategic Analysis */}
      {analysis && (
        <section className="mb-8 rounded-xl border border-border bg-bg-card p-6">
          <h3 className="mb-4 font-mono text-[11px] uppercase tracking-[2px] text-cyan">
            {t('check_preview_strat')}
          </h3>
          <div className="prose prose-sm prose-invert max-w-none text-txt-dim space-y-3">
            {analysis.split(/\n\n+/).filter(Boolean).map((p, i) => (
              <p key={i} className="text-sm leading-relaxed">{p.trim()}</p>
            ))}
          </div>
        </section>
      )}

      {/* Action Buttons */}
      <div className="flex flex-wrap justify-center gap-3 mt-8">
        <button
          onClick={handleCopyToAI}
          className="rounded-lg border border-cyan-dim bg-cyan-glow px-6 py-2.5 font-mono text-sm text-cyan transition-colors hover:bg-cyan hover:text-black"
        >
          {copied ? t('check_copied') : t('check_copy_to_ai')}
        </button>

        {data.report_id && (
          <>
            <a
              href={`${API_BASE}/report/${data.report_id}/pdf`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg border border-border px-6 py-2.5 font-mono text-sm text-txt-dim transition-colors hover:border-cyan hover:text-cyan"
            >
              {lang === 'zh' ? '下載 PDF' : 'Download PDF'}
            </a>
            <a
              href={`${API_BASE}/report/${data.report_id}/json`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-lg border border-border px-6 py-2.5 font-mono text-sm text-txt-dim transition-colors hover:border-cyan hover:text-cyan"
            >
              {lang === 'zh' ? '下載 JSON' : 'Download JSON'}
            </a>
          </>
        )}

        <button
          onClick={onReset}
          className="rounded-lg border border-border px-6 py-2.5 font-mono text-sm text-txt-dim transition-colors hover:border-cyan hover:text-cyan"
        >
          {t('check_another')}
        </button>
      </div>
    </div>
  );
}
